---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: install nginx role
      command: "ansible-galaxy install nginxinc.nginx"
      register: outpt
    - debug: var=outpt

- hosts: all
  gather_facts: no
  ignore_errors: yes
  become: yes
  #become_method: sudo
  #become_user: root
  tasks:
    - name: Include the example role
      include_role:
        name: nginxinc.nginx
